---
extends: default

# Ignoriere Ordner/Dateien, die uns nicht interessieren
ignore: |
  _site/**
  vendor/**
  node_modules/**
  assets/**

rules:
  # Hauptnerv-Faktor: lange Zeilen -> komplett deaktivieren
  line-length: disable

  # Diese Style-Regeln hatten wir schon oft am Wickel -> aus
  truthy: disable
  document-start: disable
  comments-indentation: disable
  trailing-spaces: disable
  empty-lines: disable
