---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Konstantin Thumm"
name: "Konstantin Thumm"
description: "IT-Consultant • Digitalisierung • KI & NGO"
url: "https://konstantinthumm.de"
baseurl: ""
github_username: konstantinthumm
minimal_mistakes_skin: dark. # default
search: true
lunr:
  search_within_pages: true

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Build settings
markdown: kramdown
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin
include:
  - _pages

breadcrumbs: true  # disabled by default
enable_copy_code_button: true

# Fallback für Related Posts + Post-Listen (Grid)
teaser: /assets/images/posts/spidey-600.jpg


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

repository: "konstantinthumm/konstantinthumm.github.io"
comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOP5gRyA"  # Beispielwert
    category_name: "General"
    category_id: "DIC_kwDOP5gRyM4CwPFK"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "dark_dimmed"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Profile
author:
  name: "Konstantin Thumm"
  avatar: "/assets/images/konstantinthumm-400.jpg"  # eigenes Bild später hier ablegen
  bio: "Digitale Transformation, Projektmanagement und KI<br>für wirksame und nachhaltige Projekte in NGOs und Sozialorganisationen"
  location: "Berlin, Deutschland"  # ← das zeigt die „Maps-Fahne“ + Text
  mastodon: "@konstantinthumm@social.tchncs.de"
  links:
    # - label: "Website"
    #  url: "https://konstantinthumm.de"
    #  icon: "fas fa-link"
    - label: "GitHub"
      url: "https://github.com/konstantinthumm"
      icon: "fab fa-github"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/konstantinthumm"
      icon: "fab fa-linkedin"
    - label: "Mastodon"
      url: "https://social.tchncs.de/@konstantinthumm"
      icon: "fab fa-mastodon"
    - label: "Bluesky"
      url: "https://bsky.app/profile/konstantinthumm.bsky.social"
      icon: "fab fa-bluesky"
    - label: "E-Mail"
      url: "mailto:kontakt@konstantinthumm.de"
      icon: "fas fa-envelope"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/konstantinthumm"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/konstantinthumm"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://social.tchncs.de/@konstantinthumm"
    - label: "Bluesky"
      url: "https://bsky.app/profile/konstantinthumm.bsky.social"
      icon: "fab fa-bluesky"
    - label: "E-Mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kontakt@konstantinthumm.de"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar: true
      read_time: true
      comments: true
      share: true
      related: true
      overlay_filter: 0.35
      toc: true
      toc_sticky: true
      toc_label: "Inhalt"
      toc_icon: "list-ul"  # Font-Awesome Icon (Alternative: "bars", "list")
      # Optional: nur H2/H3 aufnehmen (wenn du das nutzt)
      # toc_min: 2
      # toc_max: 3
      # TOC lässt sich in einzelnen Posts jederzeit über toc: false im Front-Matter ausnehmen.
      classes: "hero-tall wide"
      show_date: true
      teaser: /assets/images/posts/spidey-600.jpg
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

mastodon_instance: "https://social.tchncs.de"
