name: Lighthouse (manual)

on:
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g @lhci/cli@0.12.x
      - name: Run Lighthouse against production
        run: |
          lhci autorun --collect.url=https://konstantinthumm.de \
                       --upload.target=temporary-public-storage
