---
name: Link Check

on:
  pull_request:
  schedule:
    - cron: "17 3 * * 1"   # Mo 03:17 UTC (beliebig)
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Jekyll bauen, damit interne Links geprüft werden können
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: "3.2" }
      - run: |
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build --trace
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          # prüfe generierten Output + Markdown-Quellen
          args: >-
            --verbose
            --no-progress
            --max-concurrency 2
            --timeout 20
            --accept 200,206,429
            --exclude-file .lycheeignore
            ./_site
            ./
          fail: false    # <<< soft-fail: Job wird nie rot
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
