---
name: Typos Check

"on":
  push:
  workflow_dispatch: {}

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: true  # Job darf warnen, aber nicht failen
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1
        with:
          config: ./typos.toml
          files: .
