name: YAML & JSON Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML
        run: |
          pip install yamllint
          yamllint -d "{extends: default, rules: {line-length: {max: 140}}}" .
      - name: Lint JSON
        run: |
          pip install jsonlint-ng
          files=$(git ls-files "*.json") || true
          if [ -n "$files" ]; then jsonlint --quiet $files; else echo "No JSON files"; fi
